default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  database: scheduled_tweets_development
  username:  <%= ENV['POSTGRES_USER'] %>
  password:  <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: scheduled_tweets_test
  username:  <%= ENV['POSTGRES_USER'] %>
  password:  <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database:  <%= ENV['POSTGRES_DB'] %>
  username:  <%= ENV['POSTGRES_USER'] %>
  password:  <%= ENV['POSTGRES_PASSWORD'] %>
